services:
  migration:
    image: ${REGISTRY}/devtinder-server:${IMAGE_TAG}
    command: node dist/db/migrate.js
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  api:
    image: ${REGISTRY}/devtinder-server:${IMAGE_TAG}
    container_name: devtinder-api
    command: node dist/server.js
    ports: !reset []
    stop_grace_period: 30s
    environment:
      NODE_ENV: production

    depends_on:
      migration:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.75"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    image: ${REGISTRY}/devtinder-server:${IMAGE_TAG}
    container_name: devtinder-worker
    command: node dist/worker.js
    stop_grace_period: 60s
    environment:
      NODE_ENV: production
    depends_on:
      migration:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.50"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    container_name: devtinder-postgres
    deploy:
      resources:
        limits:
          memory: 512m
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  redis:
    container_name: devtinder-redis
    deploy:
      resources:
        limits:
          memory: 128m
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  frontend:
    image: ${REGISTRY}/devtinder-frontend:${IMAGE_TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt:ro

    depends_on:
      api:
        condition: service_healthy

  prometheus:
    ports: !reset []

  grafana:
    ports: !override
      - "127.0.0.1:3001:3000"
    
      
